config/routes.rb
Rails.application.routes.draw do
  resources :secondary_assets do
    resources :primary_assets
  end
  
  resources :primary_assets do
    collection do
      delete 'destroy_multiple'
    end
  end

  root to: 'visitors#index'

end

app/models/primary_asset.rb
class PrimaryAsset < ActiveRecord::Base
  has_and_belongs_to_many :secondary_assets
end

app/models/secondary_asset.rb
class SecondaryAsset < ActiveRecord::Base
  has_and_belongs_to_many :primary_assets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/primary_assets_controller.rb
class PrimaryAssetsController < ApplicationController
  before_action :set_primary_asset, only: [:show, :edit, :update, :destroy]

  # GET /primary_assets
  # GET /primary_assets.json
  def index

    if params[:secondary_asset_id]
      @primary_assets = SecondaryAsset.find_by_id(params[:secondary_asset_id]).primary_assets
    else
      @primary_assets = PrimaryAsset.all
    end

    respond_to do |format| 
      format.html { }
      format.json { render :json => @primary_assets }
    end

  end

  # GET /primary_assets/1
  # GET /primary_assets/1.json
  def show
  end

  # GET /primary_assets/new
  def new
    @primary_asset = PrimaryAsset.new
  end

  # GET /primary_assets/1/edit
  def edit
  end

  # POST /primary_assets
  # POST /primary_assets.json
  def create
    @primary_asset = PrimaryAsset.new(primary_asset_params)

    respond_to do |format|
      if @primary_asset.save
        format.html { redirect_to @primary_asset, notice: 'Primary asset was successfully created.' }
        format.json { render :show, status: :created, location: @primary_asset }
      else
        format.html { render :new }
        format.json { render json: @primary_asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /primary_assets/1
  # PATCH/PUT /primary_assets/1.json
  def update
    respond_to do |format|
      if @primary_asset.update(primary_asset_params)
        format.html { 
	  redirect_to @primary_asset, notice: 'Primary asset was successfully updated.' 
	}
        format.json { render :show, status: :ok, location: @primary_asset }
      else
        format.html { 
	  render :edit }
        format.json { render json: @primary_asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /primary_assets/1
  # DELETE /primary_assets/1.json
  def destroy
    @primary_asset.destroy
    respond_to do |format|
      format.html { redirect_to primary_assets_url, notice: 'Primary asset was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy_multiple
    params[:id].split(",").each do |id|
      PrimaryAsset.destroy(id)
    end

    respond_to do |format|
   #   format.html { redirect_to primary_assets_url, notice: 'Primary asset was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_primary_asset
      @primary_asset = PrimaryAsset.find(params[:id])
      @secondary_assets = SecondaryAsset.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def primary_asset_params
      params.require(:primary_asset).permit(:name, :description, :d, :i, :c, :t, :secondary_asset_ids =>[])
    end
end

app/controllers/secondary_assets_controller.rb
class SecondaryAssetsController < ApplicationController
  before_action :set_secondary_asset, only: [:show, :edit, :update, :destroy]

  # GET /secondary_assets
  # GET /secondary_assets.json
  def index
    @secondary_assets = SecondaryAsset.all
  end

  # GET /secondary_assets/1
  # GET /secondary_assets/1.json
  def show
  end

  # GET /secondary_assets/new
  def new
    @secondary_asset = SecondaryAsset.new
  end

  # GET /secondary_assets/1/edit
  def edit
  end

  # POST /secondary_assets
  # POST /secondary_assets.json
  def create
    @secondary_asset = SecondaryAsset.new(secondary_asset_params)

    respond_to do |format|
      if @secondary_asset.save
        format.html { redirect_to @secondary_asset, notice: 'Secondary asset was successfully created.' }
        format.json { render :show, status: :created, location: @secondary_asset }
      else
        format.html { render :new }
        format.json { render json: @secondary_asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /secondary_assets/1
  # PATCH/PUT /secondary_assets/1.json
  def update
    respond_to do |format|
      if @secondary_asset.update(secondary_asset_params)
        format.html { redirect_to @secondary_asset, notice: 'Secondary asset was successfully updated.' }
        format.json { render :show, status: :ok, location: @secondary_asset }
      else
        format.html { render :edit }
        format.json { render json: @secondary_asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /secondary_assets/1
  # DELETE /secondary_assets/1.json
  def destroy
    @secondary_asset.destroy
    respond_to do |format|
      format.html { redirect_to secondary_assets_url, notice: 'Secondary asset was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy_multiple
    params[:id].split(",").each do |id|
      SecondaryAsset.destroy(id)
    end

    respond_to do |format|
      format.json { head :no_content }
    end
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_secondary_asset
      @secondary_asset = SecondaryAsset.find(params[:id])
      @primary_assets = PrimaryAsset.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def secondary_asset_params
      params.require(:secondary_asset).permit(:name, :description, :primary_asset_ids => [])
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/primary_assets_helper.rb
module PrimaryAssetsHelper
end

app/helpers/secondary_assets_helper.rb
module SecondaryAssetsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<li><%= link_to 'Primary Assets', primary_assets_path %></li>
<li><%= link_to 'Secondary Assets', secondary_assets_path %></li>

<%#<div class="btn-group btn-group-sm" role="group" aria-label="menu">%>
  <%#<div class="dropdown">%>
    <%#<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">%>
      <%#Assets %>
      <%#<span class="caret"></span>%>
    <%#</button>%>
    <%#<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">%>
      <%#<li><%= link_to 'Primary Assets', primary_assets_path %>
      <%#</li>%>
    <%#<li><%= link_to 'Secondary Assets', secondary_assets_path %>
      <%#</li>%>
    <%#</ul>%>
  <%#</div>%>
<%#</div>%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Smsiapp" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Smsiapp" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/primary_assets/_form.html.erb
<%= simple_form_for(@primary_asset) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :d %>
    <%= f.input :i %>
    <%= f.input :c %>
    <%= f.input :t %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/primary_assets/edit.html.erb
<h1>Editing Primary Asset</h1>

<%= render 'form' %>

<%= link_to 'Show', @primary_asset %> |
<%= link_to 'Back', primary_assets_path %>

app/views/primary_assets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Primary Assets</h1>
<table id="jqgrid"></table>
<%= link_to 'New Primary asset', new_primary_asset_path %>


<div style="margin-left:20px">
  <table id="jqGrid"></table>
  <div id="jqGridPager"></div>
</div>
<script type="text/javascript">

//$.extend($.jgrid.edit, {
//  onclickSubmit: function (params, postdata) {
  //
 //postdata = JSON.stringify({params: postdata})
    //encodeURIComponent(postdata[params.myGridId + '_id']);
 // }
//});
var lastsel;
$(document).ready(function () {
  var template = "<div style='margin-left:15px;'><div> Name %> :</div><div> {CustomerID} </div>";
  template += "<div> Company bla Name: </div><div>{CompanyName} </div>";
  template += "<div> Phone: </div><div>{Phone} </div>";
  template += "<div> Postal Code: </div><div>{PostalCode} </div>";
  template += "<div> City:</div><div> {City} </div>";
  template += "<hr style='width:100%;'/>";
  template += "<div> {sData} {cData}  </div></div>";

  $("#jqGrid").jqGrid({
url: 'primary_assets',
// we set the changes to be made at client side using predefined word clientArray
//multiselect: true,
onSelectRow: function(id){
  if(id && id!==lastSel){ 
    $('#jqGrid').restoreRow(lastSel); 
    lastSel=id; 
  }
  $('#jqGrid').editRow(id, true); 
},
multikey: "shiftkey",
editurl: 'primary_assets',
datatype: "json",
colModel: [
{
name: 'id',
hidden: true,
key: true,
editrules : { required: true}
},
{
label: '<%= PrimaryAsset.human_attribute_name :name %>',
       name: 'name',
       width: 75,
       key: true,
       editable: true,
       editrules : { required: true}
},
{
label: '<%= PrimaryAsset.human_attribute_name :description %>',
       name: 'description',
       width: 140,
       editable: true // must set editable to true if you want to make the field editable
},
{
label: '<%= PrimaryAsset.human_attribute_name :av %>',
       name: 'd',
       width: 100,
       editable: true
},
{
label: '<%= PrimaryAsset.human_attribute_name :i %>',
       name: 'i',
       width: 80,
       editable: true
},
{
label: '<%= PrimaryAsset.human_attribute_name :c %>',
       name: 'c',
       width: 140,
       editable: true
},
{
label: '<%= PrimaryAsset.human_attribute_name :au %>',
       name: 't',
       width: 140,
       editable: true
}
],
  sortname: 'name',
  sortorder : 'asc',
  loadonce: true,
  viewrecords: true,
  width: 780,
  height: 200,
  rowNum: 10,
  pager: "#jqGridPager"
  });

//$("#jqGrid").jqGrid('editRow',rowid, 
// { 
//keys : true, 
//oneditfunc: function() {
//alert ("edited"); 
//}
//});


$.extend($.jgrid.defaults, {
ajaxGridOptions: { contentType: "application/json" },
ajaxRowOptions: { contentType: "application/json", async: true },
ajaxSelectOptions: { contentType: "application/json", dataType: "JSON" }
});

$.extend($.jgrid.edit, {
ajaxEditOptions: { contentType: "application/json" }});

$('#jqGrid').navGrid('#jqGridPager',
    // the buttons to appear on the toolbar of the grid
    { edit: true, add: true, del: true, search: false, refresh: false, view: false, position: "left", cloneToTop: false },
    // options for the Edit Dialog
    {
closeAfterEdit: true,
afterSubmit:function(){ $(this).jqGrid("setGridParam", {datatype:'json'}); return [true];},
mtype: "PUT",
editCaption: "The Edit Dialog",
url: 'primary_assets',
onclickSubmit: function (params, postdata) {
params.url += '/' + encodeURIComponent(postdata.jqGrid_id) + '.json';
},
serializeEditData: function(postdata) {
return (JSON.stringify({primary_asset: {name: postdata.name, description: postdata.description, d: postdata.d, i: postdata.i, c: postdata.c, t: postdata.t}}));
},
template: template,
errorTextFormat: function (data) {
return 'Error: ' + data.responseText
}
},
  // options for the Add Dialog
{
template: template,
	  errorTextFormat: function (data) {
	    return 'Error: ' + data.responseText
	  },
afterSubmit:function(){ $(this).jqGrid("setGridParam", {datatype:'json'}); return [true];},
	    closeAfterAdd: true,
	    serializeEditData: function(postdata) {
	      return (JSON.stringify({primary_asset: {name: postdata.name, description: postdata.description, d: postdata.d, i: postdata.i, c: postdata.c, t: postdata.t}}));
	    },

},
  // options for the Delete Dailog
{
mtype: "DELETE",
       url: 'primary_assets/destroy_multiple.json',
       errorTextFormat: function (data) {
	 return 'Error: ' + data.responseText
       }
});
});

</script>

app/views/primary_assets/new.html.erb
<h1>New Primary Asset</h1>

<%= render 'form' %>

<%= link_to 'Back', primary_assets_path %>

app/views/primary_assets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @primary_asset.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @primary_asset.description %>
</p>

<p>
  <strong>D:</strong>
  <%= @primary_asset.d %>
</p>

<p>
  <strong>I:</strong>
  <%= @primary_asset.i %>
</p>

<p>
  <strong>C:</strong>
  <%= @primary_asset.c %>
</p>

<p>
  <strong>T:</strong>
  <%= @primary_asset.t %>
</p>

<%= link_to 'Edit', edit_primary_asset_path(@primary_asset) %> |
<%= link_to 'Back', primary_assets_path %>

app/views/secondary_assets/_form.html.erb
<%= simple_form_for(@secondary_asset) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/secondary_assets/edit.html.erb
<h1>Editing Secondary Asset</h1>

<%= render 'form' %>

<%= link_to 'Show', @secondary_asset %> |
<%= link_to 'Back', secondary_assets_path %>

app/views/secondary_assets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Secondary Assets</h1>

<br>

<table id="jqgrid"></table>


<div style="margin-left:20px">
  <table id="jqGrid"></table>
  <div id="jqGridPager"></div>
</div>
<script type="text/javascript">

//$.extend($.jgrid.edit, {
//  onclickSubmit: function (params, postdata) {
  //
 //postdata = JSON.stringify({params: postdata})
    //encodeURIComponent(postdata[params.myGridId + '_id']);
 // }
//});
var lastsel;
$(document).ready(function () {
  var template = "<div style='margin-left:15px;'><div> Name %> :</div><div> {CustomerID} </div>";
  template += "<div> Company bla Name: </div><div>{CompanyName} </div>";
  template += "<div> Phone: </div><div>{Phone} </div>";
  template += "<div> Postal Code: </div><div>{PostalCode} </div>";
  template += "<div> City:</div><div> {City} </div>";
  template += "<hr style='width:100%;'/>";
  template += "<div> {sData} {cData}  </div></div>";

  $("#jqGrid").jqGrid({
url: 'secondary_assets',
// we set the changes to be made at client side using predefined word clientArray
//multiselect: true,
onSelectRow: function(id){
if(id && id!==lastSel){ 
$('#jqGrid').restoreRow(lastSel); 
lastSel=id; 
}
$('#jqGrid').editRow(id, true); 
},
multikey: "shiftkey",
editurl: 'secondary_assets',
datatype: "json",
colModel: [
{
name: 'id',
hidden: true,
key: true,
editrules : { required: true}
},
{
label: '<%= SecondaryAsset.human_attribute_name :name %>',
       name: 'name',
       width: 75,
       key: true,
       editable: true,
       editrules : { required: true}
},
{
label: '<%= SecondaryAsset.human_attribute_name :description %>',
       name: 'description',
       width: 140,
       editable: true // must set editable to true if you want to make the field editable
},
{
label: '<%= SecondaryAsset.human_attribute_name :av %>',
       name: 'd',
       width: 80,
       editable: true
},
{
label: '<%= SecondaryAsset.human_attribute_name :i %>',
       name: 'i',
       width: 80,
       editable: true
},
{
label: '<%= SecondaryAsset.human_attribute_name :c %>',
       name: 'c',
       width: 80,
       editable: true
},
{
label: '<%= SecondaryAsset.human_attribute_name :au %>',
       name: 't',
       width: 80,
       editable: true
}
],
  sortname: 'name',
  sortorder : 'asc',
  loadonce: true,
  viewrecords: true,
  width: 780,
  height: 200,
  rowNum: 10,
  pager: "#jqGridPager",
  subGrid: true,
  subGridRowExpanded: function(subgrid_id, row_id) {
    var subgrid_table_id, pager_id;
    var sa_id;
    subgrid_table_id = subgrid_id+"_t";
    pager_id = "p_"+subgrid_table_id;
    sa_id = $("#jqGrid").getRowData(row_id);
    $("#"+subgrid_id).html("<table id='"+subgrid_table_id+"' class='scroll'></table><div id='"+pager_id+"' class='scroll'></div>");
    jQuery("#"+subgrid_table_id).jqGrid({
url: 'secondary_assets/'+sa_id.id+'/primary_assets.json',
colModel: [
{
name: 'id',
hidden: true,
key: true,
editrules : { required: true}
},
{
label: '<%= PrimaryAsset.human_attribute_name :name %>',
name: 'name',
width: 75,
key: true,
editable: true,
editrules : { required: true}
},
{
label: '<%= PrimaryAsset.human_attribute_name :description %>',
name: 'description',
width: 140,
editable: true // must set editable to true if you want to make the field editable
},
{
label: '<%= PrimaryAsset.human_attribute_name :av %>',
       name: 'd',
       width: 80,
       editable: true
},
{
label: '<%= PrimaryAsset.human_attribute_name :i %>',
       name: 'i',
       width: 80,
       editable: true
},
{
label: '<%= PrimaryAsset.human_attribute_name :c %>',
       name: 'c',
       width: 80,
       editable: true
},
{
label: '<%= PrimaryAsset.human_attribute_name :au %>',
       name: 't',
       width: 80,
       editable: true
}]

});
}
});

//$("#jqGrid").jqGrid('editRow',rowid, 
// { 
//keys : true, 
//oneditfunc: function() {
//alert ("edited"); 
//}
//});


$.extend($.jgrid.defaults, {
ajaxGridOptions: { contentType: "application/json" },
ajaxRowOptions: { contentType: "application/json", async: true },
ajaxSelectOptions: { contentType: "application/json", dataType: "JSON" }
});

$.extend($.jgrid.edit, {
ajaxEditOptions: { contentType: "application/json" }});

$('#jqGrid').navGrid('#jqGridPager',
    // the buttons to appear on the toolbar of the grid
    { edit: true, add: true, del: true, search: false, refresh: false, view: false, position: "left", cloneToTop: false },
    // options for the Edit Dialog
    {
closeAfterEdit: true,
afterSubmit:function(){ $(this).jqGrid("setGridParam", {datatype:'json'}); return [true];},
mtype: "PUT",
editCaption: "The Edit Dialog",
url: 'secondary_assets',
onclickSubmit: function (params, postdata) {
params.url += '/' + encodeURIComponent(postdata.jqGrid_id) + '.json';
},
serializeEditData: function(postdata) {
return (JSON.stringify({secondary_asset: {name: postdata.name, description: postdata.description, d: postdata.d, i: postdata.i, c: postdata.c, t: postdata.t}}));
},
template: template,
errorTextFormat: function (data) {
return 'Error: ' + data.responseText
}
},
  // options for the Add Dialog
{
template: template,
	  errorTextFormat: function (data) {
	    return 'Error: ' + data.responseText
	  },
afterSubmit:function(){ $(this).jqGrid("setGridParam", {datatype:'json'}); return [true];},
	    closeAfterAdd: true,
	    serializeEditData: function(postdata) {
	      return (JSON.stringify({secondary_asset: {name: postdata.name, description: postdata.description, d: postdata.d, i: postdata.i, c: postdata.c, t: postdata.t}}));
	    },

},
  // options for the Delete Dailog
{
mtype: "DELETE",
       url: 'secondary_assets/destroy_multiple.json',
       errorTextFormat: function (data) {
	 return 'Error: ' + data.responseText
       }
});
});

</script>

app/views/secondary_assets/new.html.erb
<h1>New Secondary Asset</h1>

<%= render 'form' %>

<%= link_to 'Back', secondary_assets_path %>

app/views/secondary_assets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @secondary_asset.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @secondary_asset.description %>
</p>

<%= link_to 'Edit', edit_secondary_asset_path(@secondary_asset) %> |
<%= link_to 'Back', secondary_assets_path %>

app/views/visitors/index.html.erb
<!-- Page Content -->
<div class="container">

    <div class="row">
        <div class="col-lg-12 text-center">
            <h1>SMSIApp</h1>
        </div>
    </div>
    <!-- /.row -->

</div>
<!-- /.container -->